# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b096baede09da34c36fde8353bcdb2771929510152663d773a473143210e59290cff15bfc96f8abc12ce732b769fab545d97ae32ca105d84138bce9a5076668

test:
  secret_key_base: 6b37ca6b86ac30bfc2713328cbf3702bfc84928b733233d2ce0b0786c7ca41787ef335d467aaf043062ac0348f9e7feb5db7048a340cfba7f22b2d201f14d227

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
